# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='versity_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=25)),
                ('subjects', models.CharField(max_length=200)),
                ('date_line', models.CharField(max_length=25)),
                ('website_link', models.CharField(max_length=100)),
            ],
        ),
    ]
