# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versity', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us', models.CharField(max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name='versity_info',
        ),
    ]
