# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versity', '0003_auto_20160628_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='full',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(max_length=500)),
                ('conditions', models.CharField(max_length=600)),
            ],
        ),
    ]
