# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versity', '0005_partial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bachalor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='masters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='phd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=400)),
            ],
        ),
    ]
